### ISSUE TITLE
Implementing Search

### ISSUE THREAD

**Issue by tompscanlan** [OpenMeet-Team/openmeet-platform#13]
# How do we implement search?

* important that locality be part of the criteria
* I want to search groups and events

**Comment by stanislavkhatko** [comment]
@tompscanlan if you can take a look on complexity PostGIS will add maybe we should try it out instead of moving to an extra service.

**Comment by tompscanlan** [comment]
Will try following https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Appendix.PostgreSQL.CommonDBATasks.PostGIS.html

**Comment by tompscanlan** [comment]
depends on:
* openmeet-team/openmeet-api#124
* openmeet-team/openmeet-api#125
